### ISSUE TITLE
Request ARGONER for ARGON

### ISSUE THREAD

**Issue by cberys** [cchdo/params#12]
https://exchange-format.readthedocs.io/en/latest/parameters.html#argon

**Comment by DocOtak** [comment]
Hm... this seems to already exist (see the "error_name" property).

Maybe it's a display issue in the exchange docs.

https://github.com/cchdo/params/blob/9d399f21410aad9ee9d696d3216cd8f053f2e675/cchdo/params/_whp_names.py#L2760-L2786

**Comment by cberys** [comment]
Weird, it is not showing up on read the docs and also giving me an error when trying to convert to CF netCDF

**Comment by DocOtak** [comment]
Ah... it's the commit _just after_ the 0.17 release... so this will be in 0.18. https://github.com/cchdo/params/commit/44dafe95b4a0f9ea66b31280d63b73fb68c81d4d

**Comment by cberys** [comment]
Did you close this? Why am I still getting an undefined param error?

**Comment by DocOtak** [comment]
The name is already in the code/database, just not in the published pypi version. If you need to try it out before the published version is updated. Do a `pip install git+https://github.com/cchdo/params.git` to get the HEAD/prerelease version for testing.

**Comment by DocOtak** [comment]
Also a reminder that there is no support for relative uncertainties in CF yet, i.e. the uncertainty parameter must have the same units as the data parameter (so something like ARGON [UMOL/KG] with ARGONER [%] won't work)
