### ISSUE TITLE
Add NMOL/L as acceptable unit for IODATE and UREA

### ISSUE THREAD

**Issue by eaitoro** [cchdo/params#19]
Specific cruise in question that reports these data in this unit, which matches up with their cruise report/figures: [49NZ20191205](https://cchdo.ucsd.edu/cruise/49NZ20191205)

**Comment by DocOtak** [comment]
The existing UREA param has units of umol/kg. The usual volume variant would be umol/l. Can you confirm that the nmol is correct/expected? I will often start looking at the oceanographic literature for external verification of expected ranges/units for some parameter.

**Comment by eaitoro** [comment]
For IODATE: [https://doi.org/10.1016/j.dsr2.2011.02.002](https://doi.org/10.1016/j.dsr2.2011.02.002)
- this was one of the linked references in the cruise report
- this study was in the southern ocean (Atlantic sector) during the summer and found values of 400-450 nmol/L, this aligns with the magnitude of values found in this file. Although this transect had a much lower minimum value in the 100s.

For UREA: [https://doi.org/10.1002/lom3.10026](https://doi.org/10.1002/lom3.10026)
- figure 8 shows urea in nmol/L in the same order of magnitude found in this file
- however, values in this file vary *significantly* more than in that paper (minimum = 1.4, maximum = 144.4 for the referenced file versus a range of 50ish nmol/L to 125 nmol/L in the paper), perhaps just a regional difference since the study was in the s. China Sea?

**Comment by DocOtak** [comment]
This one gets a partial for now, the IODATE change goes in as proposed. I did some checks on UREA and the data we have already.

All the existing data at CCHDO have UREA in umol/kg, with ranges comparable to what is here proposed here, just smaller:
* Existing data is 0\~0.5 UMOL/KG which is ≈ 0\~500NMOL/L
* Checking though all the existing params, we do not have any mixed SI prefix units for any given param, this type of alternate unit appears somewhat unprecedented at CCHDO. Even some of the literature talking about urea will mix/swap between umol and nmol, so there might not be consensus.

I'd like to ask our science advisors for... advice on this one. I have a desire to keep the prefix consistency, i.e. the final param is umol/l and we convert from nmol/l to umol/l so the only difference between our units is mass vs volume. Pointing out that the conversion between nmol/l and umol/l is exact.

**Comment by DocOtak** [comment]
Asked Jim and Sarah at the meting on August 23. Since this is an unambiguous conversion, the advise is to convert from NMOL to UMOL by simple division by 1000 (pure SI conversions).

**Comment by DocOtak** [comment]
@cberys Where would you like the above decision documented?

**Comment by cberys** [comment]
@DocOtak it should be mentioned in the monthly report and also make an issue on the operations manual repo to add it (or you can add it somewhere but that needs a major overhaul/revision so I suggest just making an issue)

**Comment by DocOtak** [comment]
Closing since IODATE was added and the UREA decision now exists in the ops manual as an issue and won't be added as a name.
