### ISSUE TITLE
add new parameters BACT, PRO, SYN, and PEUK

### ISSUE THREAD

**Issue by cberys** [cchdo/params#2]
SYN		Synechococcus	Synechococcus Cell Count	E6/L

PEUK		Pigmented Picoeukaryotes	Picoeukaryote Cell Counts	E6/L

BACT		Bacterial Cell Count	Cell count of non pigmented heterotrophic bacterioplankton through FCM	E8/L

PROC		Prochlorophytes	Prochlorophyte Cell Count	E7/L

the units on the parameters are of the form E6/L which is 10^6 /L

These are the standard or common units used in the community for these parameters
 
These are some papers that describe similar methods used for this work.
Campbell, L. (2001). Flow cytometric analysis of autotrophic picoplankton. Methods in Microbiology: Marine Microbiology. J. H. Paul. San Diego, Academic Press: 317-341. 

Durand, M. D., R. J. Olson and S. W. Chisholm (2001). Phytoplankton population dynamics at the Bermuda Atlantic Time-series station in the Sargasso Sea. Deep Sea Research II 48(8-9): 1983-2004

PRO is the same as PROC (Prochlorococcus cell abundance)

**Comment by DocOtak** [comment]
These names were added in e34dfe0528e379e45ebbce7be18cdb66997f312c as part of the work to finish migrating the [_really_ old params table ](https://web.archive.org/web/20130430053351/https://cchdo.ucsd.edu/parameter_descriptions).
