### ISSUE TITLE
typo in CFC113 nc_var name for pmol/l units

### ISSUE THREAD

**Issue by cberys** [cchdo/params#20]
cfc_113_ 
should be
cfc_113_l

**Comment by DocOtak** [comment]
This was fixed in https://github.com/cchdo/params/commit/d5d4352fca01eea436c5fea27d27bba50689ad8d and should be in the published version on pypi.

**Comment by cberys** [comment]
How does it get published to our parameters table page?

**Comment by cberys** [comment]
I used the correct name and it was fine, it's just the typo in the
description
