### ISSUE TITLE
Proposal: Dealing with Duplicate/Replicate Parameters

### ISSUE THREAD

**Issue by DocOtak** [cchdo/params#25]
# Duplicate Parameters
The amount of replicate data being submitted to CCHDO is increasing. These replicates are often/usually done by separate analytical groups on board, they can associated with ancillary measurements (e.g. GO-SHIP Level 3) or be new methods/procedures. US GOSHIP itself is working to become a platform of opportunity for novel and developing methods. To date, we have dealt with multiple parameters by defining a new parameter if the data were considered "important enough".

Technical note: support for these duplicate parameters will need to be added to the hydro project itself, but that support starts with the parameters database so the issue is made here first.

## Proposal
Allow for any number of duplicate parameters by appending `_ALT_n` to an already defined parameter name, where n is an increasing integer starting at 1. e.g.:

`SALNTY`
`SALNTY_ALT_1`
`SALNTY_ALT_2`

With the following rules:
* Non duplicated parameters MAY NOT have and `_ALT_n` label applied, i.e. an `_ALT_n` decoration will only exist if there are 2 or more of the same parameters
* If there is a recognized primary measurement group for a given program, their measurement gets the undecorated parameter name
* The value of the units are not considered, and parameters will be considered conflicting if their names match. if the _same_ data was submitted by the same group with different units, one set of data SHOULD be considered canonical and the other omitted. e.g. if submitted phosphate data in both umol/l and umol/kg and it is clear that one was calculated from the other.

In CF/netCDF files, the suffix will be lowercased, e.g. `bottle_salinity_alt_1`

### Ancillary Variables
Variables may have ancillary data associated with them, these include: flags, uncertainties (CCHDO calls these "error"), and analytical reporting temperatures. Since all ancillary variables are optional, the restrictions on `_ALT_n` only appearing in duplicate names does not apply. For example, if primary `SALNTY` does not have flags, but `SALNTY_ALT_1` was submitted with flags, then the file would have the following variables: `SALNTY`, `SALNTY_ALT_1`, `SALNTY_ALT_1_FLAG_W` and would not contain a `SALNTY_FLAG_W` variable [^1].

[^1]: This is a contrived example for demonstration of the rules, not to argue the scientific usefulness of having flags only on the alternate variable.

#### Flags
Flags variable names are constructed by suffixing the parent parameter with `_FLAG_W,` for the purposes of flags, the parent variable of a duplicate parameter will be the base parameter concatenated with the `_ALT_n` suffix. In the salinity example above, the base variable is `SALNTY` and the duplicate parameter is `SALNTY_ALT_1`, therefore the flag column for this duplicate variable is `SALNTY_ALT_1_FLAG_W`.

In CF/netCDF files, the suffix is `_qc`, so the flag column for `bottle_salinity_alt_1` would be `bottle_salinity_alt_1_qc`

#### Uncertainty (errors)
In exchange files the uncertainty variables come from a lookup table and cannot be constructed from the parent parameter, for example, the uncertainty name for `SILCAT` is `SILUNC`, while for `DELHE3` it is `DELHER`. For the purposes of constructing alternate parameter names, these lookup names shall be considered the base parameter and will be concatenated with the `_ALT_n` value of the parent parameter. e.g. the uncertainty variable for `SILCAT_ALT_1` will have the name `SILUNC_ALT_1`. There is no requirement that `SILUNC` exist for `SILUNC_ALT_1` to be present. Having `SILUNC_ALT_1` in a data file only requires the presence of `SILCAT_ALT_1` (which itself requires the presence of `SILCAT`).

In CF/netCDF files, the uncertainty variable names are regularized and can be constructed from the parent variable name, the uncertainty variables are suffixed with _error, so the uncertainty for `silicate_alt_1` would be `silicate_alt_1_error`

#### Analytical Temperatures
Analytical temperature variable names in exchange files also come from a lookup table and will follow the same rules as uncertainties. In CF/netCDF files, the variable name also comes from a database (not constructed) and will need have the `_alt_n` suffix applied.

### Data Management Considerations
Having many replicate parameters in a data file can cause confusion for which parameter is the one that _most users_ should use. In netCDF files, we have many attributes which can be utilized to explain, both with standard metadata and human readable comments, what the duplicate parameters are. In exchange files, we only have the comments in the "header". For exchange files that do have duplicated parameters, automatically generating this "header" should be preferred.

### Other Considered Ideas
* The argo practice of simply appending a number (starting with 2 for the first duplicate) to the root parameter name was considered. It was rejected due to some parameter names ending in a number us not wanting to cause confusion.

**Comment by kkats** [comment]
I support this proposal. In addition to the comments in the header/netCDF, I always like to have the cruise document available with the bottle data.

`SALNTY_ALT_1` can be a replicate sample or salinity calculated from measured density. I agree with the paragraph under `Data Management Consideration` that this possible ambiguity be avoided with comments in netCDF or header in the exchange format. There might be a case where it is not obvious what a particular `ALT` means and CCHDO staff might need to dig the cruise report. It can be an option to just comment "refer to cruise report for the definition of ALT". In the worse case of no report available -- maybe comment "ask PI for the meaning of ALT".

**Comment by DocOtak** [comment]
@kkats It is always nice when we have the cruise report available for reference, sadly this isn't always provided alongside the data, there are also cases where the cruise report has been published by some large publisher and we are unable to do anything but link to it.

For the specific case of salinity, it is a _really_ important variable in oceanography. We have several names at CCHDO that reflect this:
* [CTDSVLSAL](https://exchange-format.readthedocs.io/en/latest/parameters.html#ctdsvlsal) for sound velocity based absolute salinity
* [DNSSAL](https://exchange-format.readthedocs.io/en/latest/parameters.html#dnssal) for density based calculated absolute salinity
* [SALNTY](https://exchange-format.readthedocs.io/en/latest/parameters.html#salnty) for conductivity based calculated practical salinity

For the above, I would not support combining them into a single SALNTY and making `_ALT_n` names for them. I would however combine the following:
* [DNSSAL2](https://exchange-format.readthedocs.io/en/latest/parameters.html#dnssal2) -> DNSSAL_ALT_1 (this is a replicate of DNSSAL)
* [SALNTY_DNSSAL](https://exchange-format.readthedocs.io/en/latest/parameters.html#salnty-dnssal) -> SALNTY_ALT_1 (this was measured in a different lab than the SALNTY variable)
* [SALNTY_DNSSAL2](https://exchange-format.readthedocs.io/en/latest/parameters.html#salnty-dnssal2) -> SALNTY_ALT_2 (replicate measurement on a different instrument but in the same lab as SALNTY_ALT_1)
