### ISSUE TITLE
Broken reference link for CTDBETA700, CTDBBP700, and CTDBETA650_124

### ISSUE THREAD

**Issue by eaitoro** [cchdo/params#38]
SOCCOM link to Boss, E.B. and N. Haëntjens, 2016 has changed. 

new link: [https://soccom.princeton.edu/sites/g/files/toruqf5341/files/documents/SOCCOM_2016-1_Bio-optics-primer.pdf](https://soccom.princeton.edu/sites/g/files/toruqf5341/files/documents/SOCCOM_2016-1_Bio-optics-primer.pdf)

**Comment by DocOtak** [comment]
Wish they would stick that publication on zenodo or something so it would be permanently someplace.
