### ISSUE TITLE
undefined params for P18 33RO20161119

### ISSUE THREAD

**Issue by cberys** [cchdo/params#5]
cchdo.hydro.exchange.exceptions.ExchangeParameterUndefError: missing parameter def ('14C-DOCERR', '/MILLE')
cchdo.hydro.exchange.exceptions.ExchangeParameterUndefError: missing parameter def ('13C-DOC', '/MILLE')
cchdo.hydro.exchange.exceptions.ExchangeParameterUndefError: missing parameter def ('D15N_NO3_ERROR', '/MILLE')
cchdo.hydro.exchange.exceptions.ExchangeParameterUndefError: missing parameter def ('D18O_NO3', '/MILLE')

**Comment by DocOtak** [comment]
On review of existing bottle files at CCHDO the following actions are needed:

* Units of `/MILLE` added to the existing `D15N_NO3` name
  * Add D15N_NO3_ERROR as the error/uncertainty name for this parameter (automatically has the same units)
* Add `14C-DOCERR` as the error/uncertainty name for `14C-DOC`
* Add `D18O_NO3` with units of `/MILLE`
  * While in there, add `D18O_NO3_ERROR` as the error/uncertainty name.
