### ISSUE TITLE
CHLORA with units MG/M3

### ISSUE THREAD

**Issue by cberys** [cchdo/params#7]
Appears to be right per cruise report 

https://cchdo.ucsd.edu/cruise/33RR20160208

> Samples collected at 200m and
> below were effectively zero in most cases, putting a tentative lower
> limit for chlorophyll determination at 0.01 mg/m^3.

but I couldn't track down this reference 

> Analysis: The acetone extracts were analyzed using the acidification
> technique [Mueller2003] on a Turner Designs AU-10 fluorometer with the
> standard chlorophyll fluorescence set.

**Comment by DocOtak** [comment]
Currently CHLORA with MG/M^3 units is aliased to UG/L units. This conversion is exact: 1 MG/M^3 = 1 UG/L. This differs from the CTD fluorometer which has units of MG/M^3 (old exchange docs list it as MG/CUM).

Least amount of change is to map MG/M3 to UG/L via the aliasing mechanism.

**Comment by cberys** [comment]
@DocOtak  I think I would vote for the aliasing 

If I understand correctly then it would remain MG/M^3 in the file? Or is it the opposite?
