### ISSUE TITLE
XENON, KRYPTON

### ISSUE THREAD

**Issue by cberys** [cchdo/params#8]
## Request

XENON (units: NMOL/KG)
XENON_FLAG_W
XENONER (units: NMOL/KG)

KRYPTON (units: NMOL/KG) 
KRYPNON_FLAG_W
KRYPNONER (units: NMOL/KG)

## Context

This is for 33RO20150525
https://cchdo.ucsd.edu/cruise/33RO20150525

I couldn't really find any reference to methods in any of the cruise reports, even the ones that had a helium/tritium section.

The units were the same in previous uses.

## Also found in ('prior art'):

33RO20150410 (leg 1 of this cruise)
https://cchdo.ucsd.edu/cruise/33RO20150410

has data values and XENONER, KRYPTONER error columns

320620180309
https://cchdo.ucsd.edu/cruise/320620180309

has no data values but has flag 1s in flag column, no XENONER, KRYPTONER error columns

## Additional Information 

from the submission note:

File Submission William J Jenkins
P16_Helium_Isotopes_and_Noble_Gases.xlsx (download) #248d0
Date: 2018-08-30
Current Status: merged
Notes
This data set includes measurements for helium isotopes, plus helium and neon concentrations. In addition, it contains 3 NEW data types which are the concentrations of three other noble gases (Argon, Krypton, and Xenon). The measurement units  and ranges for the noble gases are listed below (note that the units are the same except for Argon):

Helium: nanomoles/kg, range 1.500 to 2.500

Neon: nanomoles/kg, range 6.000 to 10.000

Argon: micromoles/kg, range 8.000 to 25.000

Krypton: nanomoles/kg, range 1.800 to 6.000

Xenon: nanomoles/kg, range 0.2000 to 0.9000

Please don't hesitate to contact me if you have questions.

**Comment by DocOtak** [comment]
Looks like these were added in [v0.1.18](https://github.com/cchdo/params/releases/tag/v0.1.18) but the issue wasn't closed
