### ISSUE TITLE
DIC and TCARBN. Should 14C_DIC be replaced with the name TCARBN or DIC added as an alternate name?

### ISSUE THREAD

**Issue by lmerchant** [cchdo/params#9]
For the cruise https://cchdo.ucsd.edu/cruise/33RO20131223, the bottle file has the parameter 14C_DIC, and I was wondering what it should be replaced with, if anything.

In the latest parameter list, DELC13 and DELC14 are defined in terms of TCARBN or DIC, but DIC doesn't exist as its own parameter.

Description from DELC13
Enrichment of 13C vs 12C in dissolved inorganic carbon (DIC or TCARBN) compared to a reference standard usually VPDB. This is usually written as lower case delta δ13C.

or is TCARBN standing for DIC?  Could DIC be a possible alternate name along with TCARBN or just stick with TCARBN. I've only heard the term DIC, so that's why I'm wondering about it. 

I found the following information on the standard CF name and TCARBN

On the CCHDO parameter description, the TCARBN standard name is moles_of_dissolved_inorganic_carbon_per_unit_mass_in_sea_water

And I see moles_of_dissolved_inorganic_carbon_per_unit_mass_in_sea_water describes Dissolved inorganic carbon from http://cfconventions.org/Data/cf-standard-names/79/build/cf-standard-name-table.html

And from https://www.bco-dmo.org/dataset-parameter/525599, they describe TCARBN as Total dissolved inorganic carbon (TCO2).

**Comment by DocOtak** [comment]
For our purposes, DIC, TCO2, and TCARBN are equivalent parameters, TCARBN has been the name we've used for a very long time (since at least 1990).

My guess is that for this cruise, 14C_DIC should have been removed/replaced with when the DELC14 data was merged in. (i.e. remove the 14C_DIC column cc for confirmation @cberys)

DELC13 and DELC14 does not depend on the actual concentration of TCARBN, so it's fine if it is missing.

**Comment by cberys** [comment]
Ah yes that's right, sorry Lynne for not recognizing that earlier today. Maybe it would be good to add 14c-dic as an alias, it does show up sometimes

**Comment by DocOtak** [comment]
I can add that as an alias, but for this file, it would just change the error to a Duplicated Parameter one rather than unknown.

**Comment by lmerchant** [comment]
Thanks. I’ll do that.

**Comment by cberys** [comment]
Would the error list the duplicated params? That would probably be enough

**Comment by cberys** [comment]
Hmm ok this might be a "pre-wash" consideration, although having it on the params table as an alias is still a good idea I think

**Comment by cberys** [comment]
I would vote for adding 14C-DIC as an alias. I need to look for an example file - there shouldn't be one in the dataset. 

see file 12255 as an example https://cchdo.ucsd.edu/data/12255/A10%202011%20DOC%20DIC%2014C%20Druffel.xlsx

**Comment by DocOtak** [comment]
Closing this in favor of #16
